 # To execute this docker-compose yml file use `docker-compose -f <file_name> up`
# Add the `-d` flag at the end for detached execution
version: "3"
services:
  selenium-hub:
    image: selenium/hub:latest
    container_name: selenium-hub
    restart: always
    ports:
      - "4444:4444"
  chrome:
    image: selenium/node-chrome-debug:latest
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
  firefox:
    image: selenium/node-firefox-debug:latest
    shm_size: '1gb'
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
  search-module:
    image: karanagarwal1997/selenium-docker:latest
    container_name: search-module
    environment:
      - HUB_HOST=selenium-hub
      - MODULE=search-module.xml
    depends_on:
      - chrome
      - firefox
    volumes:
      - ./search-result:/usr/share/udemy/test-output
  book-flight-module:
    image: karanagarwal1997/selenium-docker:latest
    container_name: book-flight-module
    environment:
      - HUB_HOST=selenium-hub
      - MODULE=book-flight-module.xml
      - BROWSER=firefox
    depends_on:
      - chrome
      - firefox
    volumes:
      - ./book-result:/usr/share/udemy/test-output